"use client";
import Link from "next/link";
import { useTokenCheck } from "@/lib/hooks/useTokenCheck";
import { Button } from "@/components/ui/button";

export function Hero() {
  const { hasToken, loading } = useTokenCheck();

  return (
    <section className="py-32 text-center relative overflow-hidden">
      {/* Linear-style gradient mesh background */}
      <div
        className="absolute inset-0 -z-10 opacity-20"
        style={{
          background: "radial-gradient(ellipse at 30% 50%, rgba(94,106,210,0.15) 0%, transparent 70%), radial-gradient(ellipse at 70% 50%, rgba(113,112,255,0.08) 0%, transparent 70%)",
        }}
        aria-hidden="true"
      />
      <div className="container mx-auto px-4">
        <h1 className="text-5xl font-medium tracking-tight sm:text-6xl md:text-7xl text-balance animate-fade-in-up text-text-primary font-feature-settings-cv01-ss03" style={{ letterSpacing: "-1.056px" }}>
          RepoNarrate
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-text-secondary animate-fade-in-up animate-delay-100 text-pretty leading-relaxed">
          Connect your GitHub repo. Get human-readable changelogs, categorized commits,
          and semantic search. All generated by AI.
        </p>
        <div className="mt-12 animate-fade-in-up animate-delay-200">
          {loading ? (
            <div className="h-11 w-48 bg-muted rounded-md animate-pulse mx-auto" />
          ) : hasToken ? (
            <Link href="/dashboard">
              <Button size="lg" className="btn-linear-primary px-8 py-3 text-base font-medium">
                Go to Dashboard &rarr;
              </Button>
            </Link>
          ) : (
            <a href={`${process.env.NEXT_PUBLIC_API_URL}/auth/github`}>
              <Button size="lg" className="btn-linear-primary px-8 py-3 text-base font-medium">
                Get started free &rarr;
              </Button>
            </a>
          )}
        </div>
      </div>
    </section>
  );
}
