"use client";
import Link from "next/link";
import { useTokenCheck } from "@/lib/hooks/useTokenCheck";
import { Button } from "@/components/ui/button";

export function Hero() {
  const { hasToken, loading } = useTokenCheck();

  return (
    <section className="py-24 text-center">
      <div className="container mx-auto px-4">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
          RepoNarrate
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground">
          Connect your GitHub repo. Get human-readable changelogs, categorized commits,
          and semantic search. All generated by AI.
        </p>
        <div className="mt-10">
          {loading ? (
            <div className="h-11 w-48 bg-muted rounded animate-pulse mx-auto" />
          ) : hasToken ? (
            <Link href="/dashboard">
              <Button size="lg" className="px-8">
                Go to Dashboard &rarr;
              </Button>
            </Link>
          ) : (
            <a href={`${process.env.NEXT_PUBLIC_API_URL}/auth/github`}>
              <Button size="lg" className="px-8">
                Get started free &rarr;
              </Button>
            </a>
          )}
        </div>
      </div>
    </section>
  );
}
