import Link from "next/link";
import { Button } from "@/components/ui/button";
import { LandingAuthActions } from "@/components/landing/LandingAuthActions";

export function Hero() {
  return (
    <section className="relative flex min-h-screen items-center justify-center overflow-hidden bg-surface-0">
      {/* Hero background image */}
      <div
        className="absolute inset-0 z-0 bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: "url(/hero-bg.png)" }}
        aria-hidden="true"
      />

      {/* Gradient overlay to blend image */}
      <div
        className="pointer-events-none absolute inset-0 z-5"
        aria-hidden="true"
        style={{
          background:
            "linear-gradient(135deg, hsl(var(--surface-0) / 0.88) 0%, hsl(var(--surface-0) / 0.70) 30%, hsl(var(--surface-0) / 0.35) 55%, transparent 85%)",
        }}
      />

      {/* Hero section bottom shadow/depth */}
      <div
        className="pointer-events-none absolute bottom-0 left-0 right-0 z-10"
        aria-hidden="true"
        style={{
          height: "120px",
          boxShadow: "inset 0 -40px 40px hsl(var(--surface-1) / 0.8), 0 4px 20px rgba(0,0,0,0.3)",
        }}
      />

      {/* Atmospheric background layers */}
      <div className="pointer-events-none absolute inset-0 z-10 overflow-hidden" aria-hidden="true">
        <div className="corner-shine-tl" />
        <div className="corner-shine-tr" />
        <div className="corner-shine-bl" />
        <div className="corner-shine-br" />
        <div className="hero-spotlight" />

        <div className="hero-orb hero-orb-1" />
        <div className="hero-orb hero-orb-2" />
        <div className="hero-orb hero-orb-3" />
        <div className="hero-orb hero-orb-4" />
      </div>

      {/* Content */}
      <div className="container relative z-20 mx-auto flex flex-col items-center px-4 py-32 text-center">
        <div className="animate-fade-in-up mb-8 inline-flex items-center gap-2 rounded-full border border-border-standard bg-surface-2/60 px-3 py-1.5 backdrop-blur-sm">
          <span className="badge-linear-success" />
          <span className="text-xs font-medium tracking-wide text-text-secondary">AI-Powered GitHub Intelligence</span>
        </div>

        <h1 className="animate-fade-in-up animate-delay-100 text-5xl font-medium tracking-tight text-balance text-text-primary sm:text-6xl md:text-7xl lg:text-8xl font-feature-settings-cv01-ss03" style={{ letterSpacing: "-0.03em", textShadow: "0 2px 12px rgba(0,0,0,0.4)" }}>
          RepoNarrate
        </h1>

        <p className="animate-fade-in-up animate-delay-200 mx-auto mt-6 max-w-2xl text-pretty text-lg leading-relaxed text-text-secondary md:text-xl" style={{ textShadow: "0 1px 6px rgba(0,0,0,0.3)" }}>
          Connect your GitHub repo. Get human-readable changelogs, categorized commits, and semantic search — all generated by AI.
        </p>

        <div className="animate-fade-in-up animate-delay-300 mt-10 flex flex-col items-center gap-4 sm:flex-row">
          <LandingAuthActions variant="hero" />
          <Button asChild variant="outline" size="lg" className="btn-linear-ghost px-6 py-3 text-base font-medium">
            <Link href="#features">Learn More</Link>
          </Button>
        </div>

        <div className="animate-fade-in-up animate-delay-500 mt-16 flex flex-col items-center gap-3">
          <span className="text-xs uppercase tracking-widest text-text-tertiary">Trusted by developers worldwide</span>
          <div className="flex items-center gap-2">
            <div className="flex -space-x-2">
              <div className="h-7 w-7 rounded-full border-2 border-surface-0 bg-gradient-to-tr from-brand-indigo to-brand-violet" />
              <div className="h-7 w-7 rounded-full border-2 border-surface-0 bg-gradient-to-tr from-success-green to-success-emerald" />
              <div className="h-7 w-7 rounded-full border-2 border-surface-0 bg-gradient-to-tr from-brand-hover to-brand-violet" />
            </div>
            <span className="text-xs text-text-quaternary">Join 2,000+ developers</span>
          </div>
        </div>
      </div>
    </section>
  );
}
